### ISSUE TITLE
returnの位置

### ISSUE THREAD

**Issue by c0a2108119** [nisiyama158/ProjExD#11]
https://github.com/nisiyama158/ProjExD/blob/30116edb43c350adbcbde4449da200c9e759b16b/ex04/dodge_bomb.py#L15
elseを一行で書くのなら、ifも一行で書いてしまった方がわかりやすいのではないだろうか？

**Comment by nisiyama158** [comment]
確かにそう感じたのでelseの文を1行にまとめました。ありがとうございます。
