### ISSUE TITLE
ポップアップ警告かentryに表示するかのどちらかでいいと思う。ポップアップ中しかentryにerrorが表示されないなら、entryに書かなくてもよいのでは？

### ISSUE THREAD

**Issue by c0a2108119** [nisiyama158/ProjExD#4]
https://github.com/nisiyama158/ProjExD/blob/902bce75bfe620e6f55be4c132338fb192f8a685/ex02/calc.py#L16

**Comment by nisiyama158** [comment]
確かにそうなので、ポップアップ後に即座に消す部分を消去して、メッセージが残るように変更しました。
