### ISSUE TITLE
文字列が入力された(NameError)、0で割った(ZeroDivisionError)などエラーごとに分けてもいいかもしれませんね

### ISSUE THREAD

**Issue by kotaokuda** [nisiyama158/ProjExD#5]
https://github.com/nisiyama158/ProjExD/blob/902bce75bfe620e6f55be4c132338fb192f8a685/ex02/calc.py#L15

**Comment by nisiyama158** [comment]
おっしゃるとおり、エラーで分けるように変更しました。ありがとうございます。
