### ISSUE TITLE
自分には思いつかないが…

### ISSUE THREAD

**Issue by c0a21029** [nisiyama158/ProjExD#6]
https://github.com/nisiyama158/ProjExD/blob/902bce75bfe620e6f55be4c132338fb192f8a685/ex02/calc.py#L45
％演算したらいい感じに短縮できそうじゃないですか？

**Comment by nisiyama158** [comment]
％演算が何のことを言っているかは理解できていませんが、数字のボタンも記号も全て同じリストに入れれば確かに短縮は出来そうだと感じました。
しかしそうした後に修正を入れる時、相当面倒になると思われるので今回は見送らせていただきます。ありがとうございます。
