### ISSUE TITLE
あってもいいと思うけど、なくても作れそう？

### ISSUE THREAD

**Issue by c0a2108119** [nisiyama158/ProjExD#8]
https://github.com/nisiyama158/ProjExD/blob/f73ec69481cced92d24a18f52ab75a44f336b491/ex03/maze.py#L13
わざわざCount_up()を作らなくてもtime.time()で計測できると思うが、count_upを作ったことには意図があるのか？

**Comment by nisiyama158** [comment]
他の方のプログラムを見て同じくそう感じたので修正しました。
time.time()を使用して作成しました。ご指摘ありがとうございます。
